spring:
  datasource:
    url: jdbc:mysql://${testDbIp:127.0.0.1}:3306/file_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:hodo0927}
  jpa:
    hibernate:
      ddl-auto: create